language: node_js
node_js:
  - '10'
script:
  - npm install -g yarn
  - yarn
  - yarn build
cache:
  directories:
  - node_modules
deploy:
  provider: s3
  access_key_id: ${S3_ACCESS_KEY}
  secret_access_key: ${S3_SECRET_ACCESS_KEY}
  bucket: ${S3_BUCKET}
  region: ${S3_REGION}
  skip_cleanup: true
  local_dir: dist
  upload-dir: dev/design/designsystem/${VERSION}
  on:
    branch: ${DEPLOY_BRANCH}
notifications:
# TODO: use var
  slack: gotitai:jP3x4ahOD7ygOkB2tegwGj0k
